### ISSUE TITLE
sitemap.xml generating a syntax error 

### ISSUE THREAD

**Issue by sg-modlab** [statamic/seo-pro#114]
Getting the following error 

<img width="1212" alt="image" src="https://user-images.githubusercontent.com/529067/91201444-6f1c5280-e6ce-11ea-92c2-5d5f4e02bdf3.png">

**Support Details**
Statamic 3.0.0 Pro
Laravel 7.25.0
PHP 7.4.9
statamic/seo-pro 2.0.8

Here's the log entry:

```
[2020-08-25 15:14:21] staging.ERROR: syntax error, unexpected 'version' (T_STRING) on line 1 of:

<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">

tag_pair_36edd2d3d07b194308f0b3164914ca8d

</urlset>
 {"exception":"[object] (Facade\\Ignition\\Exceptions\\ViewException(code: 0): syntax error, unexpected 'version' (T_STRING) on line 1 of:

<?xml version=\"1.0\" encoding=\"UTF-8\"?>
<urlset xmlns=\"http://www.sitemaps.org/schemas/sitemap/0.9\">

tag_pair_36edd2d3d07b194308f0b3164914ca8d

</urlset>
 at /srv/users/serverpilot/apps/mod-lab/vendor/statamic/seo-pro/src/../resources/views/generated/sitemap.antlers.html:0)
[stacktrace]
#0 /srv/users/serverpilot/apps/mod-lab/vendor/statamic/cms/src/View/Antlers/Parser.php(1288): ()
#1 /srv/users/serverpilot/apps/mod-lab/vendor/statamic/cms/src/View/Antlers/Parser.php(695): Statamic\\View\\Antlers\\Parser->parsePhp('<?xml version=\"...')
#2 /srv/users/serverpilot/apps/mod-lab/vendor/statamic/cms/src/View/Antlers/Parser.php(173): Statamic\\View\\Antlers\\Parser->parseConditionPairs('<?xml version=\"...', Array)
#3 /srv/users/serverpilot/apps/mod-lab/vendor/statamic/cms/src/View/Antlers/Parser.php(131): Statamic\\View\\Antlers\\Parser->parse('<?xml version=\"...', Array)
#4 /srv/users/serverpilot/apps/mod-lab/vendor/statamic/cms/src/View/Antlers/Engine.php(89): Statamic\\View\\Antlers\\Parser->parseView('/srv/users/serv...', '<?xml version=\"...', Array)
#5 /srv/users/serverpilot/apps/mod-lab/vendor/laravel/framework/src/Illuminate/View/View.php(139): Statamic\\View\\Antlers\\Engine->get('/srv/users/serv...', Array)
#6 /srv/users/serverpilot/apps/mod-lab/vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\\View\\View->getContents()
#7 /srv/users/serverpilot/apps/mod-lab/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\\View\\View->renderContents()
#8 /srv/users/serverpilot/apps/mod-lab/vendor/statamic/seo-pro/src/Http/Controllers/SitemapController.php(19): Illuminate\\View\\View->render()
#9 /srv/users/serverpilot/apps/mod-lab/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(383): Statamic\\SeoPro\\Http\\Controllers\\SitemapController->Statamic\\SeoPro\\Http\\Controllers\\{closure}()
#10 /srv/users/serverpilot/apps/mod-lab/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php(383): Illuminate\\Cache\\Repository->remember('seo-pro.sitemap', Object(Carbon\\Carbon), Object(Closure))
#11 /srv/users/serverpilot/apps/mod-lab/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\\Cache\\CacheManager->__call('remember', Array)
#12 /srv/users/serverpilot/apps/mod-lab/vendor/statamic/seo-pro/src/Http/Controllers/SitemapController.php(20): Illuminate\\Support\\Facades\\Facade::__callStatic('remember', Array)
#13 [internal function]: Statamic\\SeoPro\\Http\\Controllers\\SitemapController->show()
#14 /srv/users/serverpilot/apps/mod-lab/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#15 /srv/users/serverpilot/apps/mod-lab/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('show', Array)
#16 /srv/users/serverpilot/apps/mod-lab/vendor/laravel/framework/src/Illuminate/Routing/Route.php(239): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Statamic\\SeoPro\\Http\\Controllers\\SitemapController), 'show')
#17 /srv/users/serverpilot/apps/mod-lab/vendor/laravel/framework/src/Illuminate/Routing/Route.php(196): Illuminate\\Routing\\Route->runController()
#18 /srv/users/serverpilot/apps/mod-lab/vendor/laravel/framework/src/Illuminate/Routing/Router.php(685): Illuminate\\Routing\\Route->run()
#19 /srv/users/serverpilot/apps/mod-lab/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#20 /srv/users/serverpilot/apps/mod-lab/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#21 /srv/users/serverpilot/apps/mod-lab/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#22 /srv/users/serverpilot/apps/mod-lab/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(77): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#23 /srv/users/serverpilot/apps/mod-lab/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#24 /srv/users/serverpilot/apps/mod-lab/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#25 /srv/users/serverpilot/apps/mod-lab/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#26 /srv/users/serverpilot/apps/mod-lab/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#27 /srv/users/serverpilot/apps/mod-lab/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
#28 /srv/users/serverpilot/apps/mod-lab/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#29 /srv/users/serverpilot/apps/mod-lab/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#30 /srv/users/serverpilot/apps/mod-lab/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#31 /srv/users/serverpilot/apps/mod-lab/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#32 /srv/users/serverpilot/apps/mod-lab/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#33 /srv/users/serverpilot/apps/mod-lab/vendor/statamic/cms/src/StaticCaching/Middleware/Retrieve.php(34): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#34 /srv/users/serverpilot/apps/mod-lab/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\StaticCaching\\Middleware\\Retrieve->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#35 /srv/users/serverpilot/apps/mod-lab/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#36 /srv/users/serverpilot/apps/mod-lab/vendor/laravel/framework/src/Illuminate/Routing/Router.php(687): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#37 /srv/users/serverpilot/apps/mod-lab/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#38 /srv/users/serverpilot/apps/mod-lab/vendor/laravel/framework/src/Illuminate/Routing/Router.php(628): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#39 /srv/users/serverpilot/apps/mod-lab/vendor/laravel/framework/src/Illuminate/Routing/Router.php(617): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#40 /srv/users/serverpilot/apps/mod-lab/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#41 /srv/users/serverpilot/apps/mod-lab/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#42 /srv/users/serverpilot/apps/mod-lab/vendor/statamic/cms/src/Http/Middleware/CheckMultisite.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#43 /srv/users/serverpilot/apps/mod-lab/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CheckMultisite->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#44 /srv/users/serverpilot/apps/mod-lab/vendor/statamic/cms/src/Http/Middleware/PoweredByHeader.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#45 /srv/users/serverpilot/apps/mod-lab/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\PoweredByHeader->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#46 /srv/users/serverpilot/apps/mod-lab/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(58): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#47 /srv/users/serverpilot/apps/mod-lab/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#48 /srv/users/serverpilot/apps/mod-lab/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#49 /srv/users/serverpilot/apps/mod-lab/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#50 /srv/users/serverpilot/apps/mod-lab/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#51 /srv/users/serverpilot/apps/mod-lab/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#52 /srv/users/serverpilot/apps/mod-lab/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#53 /srv/users/serverpilot/apps/mod-lab/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#54 /srv/users/serverpilot/apps/mod-lab/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#55 /srv/users/serverpilot/apps/mod-lab/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#56 /srv/users/serverpilot/apps/mod-lab/vendor/fruitcake/laravel-cors/src/HandleCors.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#57 /srv/users/serverpilot/apps/mod-lab/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#58 /srv/users/serverpilot/apps/mod-lab/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#59 /srv/users/serverpilot/apps/mod-lab/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#60 /srv/users/serverpilot/apps/mod-lab/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#61 /srv/users/serverpilot/apps/mod-lab/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(140): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#62 /srv/users/serverpilot/apps/mod-lab/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(109): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#63 /srv/users/serverpilot/apps/mod-lab/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#64 {main}
```

**Comment by jesseleite** [comment]
Fixed in the above commit 👍

If you've published the `sitemap.antlers.html` view to your `resources/views/vendor` folder, you'll either need to delete it, or update the first line to `{{ xml_header }}`.

If for whatever reason you need to customize the XML header, you'll need to disable short tags in your php.ini file.

**Comment by jasonvarga** [comment]
(Seth, you probably don't want short tags enabled on your server anyway. It might be a good idea to turn them off)

In your php ini file:

```
short_open_tag = Off
```

**Comment by sg-modlab** [comment]
Will check in on that. Just using basic ServerPilot setup.

**Comment by sg-modlab** [comment]
Will keep an eye out for new tagged release to confirm. Thank you both!
